# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet restore
  displayName: 'Restoring packages'
- task: DotNetCoreCLI@2
  displayName: 'Building application'
  inputs:
    command: 'build'
    arguments: '--configuration $(BuildConfiguration) --no-restore'
- task: DotNetCoreCLI@2
  displayName: "Running tests"
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --logger trx --collect "Code coverage"'
- task: DotNetCoreCLI@2
  displayName: 'Publishing app'
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '-c $(buildConfiguration) -o $(Build.StagingDirectory)/ci-build --no-build'
    zipAfterPublish: false
    modifyOutputPath: false
- task: ArchiveFiles@2
  displayName: 'Archiving files'
  inputs:
    rootFolderOrFile: '$(Build.StagingDirectory)/ci-build'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/altVStrefaRP-$(Build.BuildNumber).zip'
    replaceExistingArchive: true
- task: PublishPipelineArtifact@1
  displayName: 'Publishing pipeline artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/altVStrefaRP-$(Build.BuildNumber).zip'
    artifact: 'altVStrefaRP-$(Build.BuildNumber)'